app = "pyragogy-chatbot"

[build]
  dockerfile = "./Dockerfile"

[env]
  PORT = "3000"
  HOST = "0.0.0.0"  # 👈 Aggiunta cruciale per esporre Flowise su Fly.io

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

