app = "pyragogy-chatbot"

[build]
  dockerfile = "./Dockerfile"

[env]
  PORT = "3000"
  HOST = "0.0.0.0"

[processes]
  app = "flowise start"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

