# fly.toml
# ... (resto del file come prima, inclusa la sezione [env])

[processes]
  # Tentativo di passare host/port come argomenti
  app = "flowise start --host 0.0.0.0 --port 3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  processes = ["app"] # Assicurati che questo sia corretto

  # ... (resto della sezione services)
