# fly.toml
app = "pyragogy-chatbot"

[build]
  dockerfile = "./Dockerfile"

[env]
  PORT = "3000"
  HOST = "0.0.0.0"

# Sezione PROCESSI - Deve esserci e definire il nome 'app'
[processes]
  app = "flowise start" 

# Sezione SERVIZI - Deve fare riferimento al nome 'app' nell'array
[[services]]
  internal_port = 3000
  protocol = "tcp"
  processes = ["app"] # <<< FONDAMENTALE: nome del processo tra [""]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
