app = "pyragogy-chatbot"

[env]
PORT = "3000"
FLOWISE_USERNAME = "admin"
FLOWISE_PASSWORD = "peerpower2025"
OPENAI_API_KEY = "sk-..."                      # ← Inserisci la tua
PINECONE_API_KEY = "..."                       # ← Inserisci la tua
PINECONE_ENVIRONMENT = "us-east-1-gcp"
PINECONE_INDEX = "your_index_name"
DATABASE_URL = "mongodb+srv://admin:peerpass2025@cluster0.buihalo.mongodb.net/flowise?retryWrites=true&w=majority&appName=Cluster0"

[mounts]
  source = "flowise_data"
  destination = "/root/.flowise"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443

