# fly.toml
app = "pyragogy-chatbot"

[build]
  dockerfile = "./Dockerfile"

[env]
  PORT = "3000"
  HOST = "0.0.0.0"

# 1. DEFINISCI IL PROCESSO QUI
[processes]
  # Qui definisci un nome (es. "app") e il comando da eseguire
  app = "flowise start"  # O "flowise start --host 0.0.0.0 --port 3000" se serve

# 2. FAI RIFERIMENTO AL NOME DEL PROCESSO ("app") QUI
[[services]]
  internal_port = 3000
  protocol = "tcp"
  # Questa riga deve usare il nome definito in [processes], cioè "app"
  processes = ["app"] 

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
