app = "pyragogy-chatbot"

# File: Peeragogy_Chatbot/Dockerfile
FROM flowiseai/flowise
EXPOSE 3000
CMD ["flowise", "start"]

---
# 🛫 fly.toml
# File: Peeragogy_Chatbot/fly.toml
app = "pyragogy-chatbot"

[build]
  dockerfile = "./Dockerfile"

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
